config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :users, except: %i(new edit) do
      get :count, on: :collection
      resource :name, only: %w(show)
      resource :shop, except: %i(new edit)
    end
  end

  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
# == Schema Information
#
# Table name: monsters
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Monster
  include Mongoid::Document

  field :name, type: String
  field :description, type: String

	validates :name, presence: true
end

app/models/robot.rb
# == Schema Information
#
# Table name: robots
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Robot < ApplicationRecord
end

app/models/shop.rb
class Shop
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user

  field :name
  field :description

  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  age        :integer
#  gender     :string
#  address    :text
#

class User
  include Mongoid::Document
  include Mongoid::Timestamps

  GENDERS = %w(male female others).freeze
  ADDRESS_ACCESSOR_KEYS = %i(country address_1 address_2).freeze

  field :first_name, type: String
  field :last_name,  type: String
  field :age,        type: Integer
  field :gender,     type: String
  field :address,    type: Hash

  validates :first_name, :last_name, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 0 }
  validates :gender, inclusion: { in: GENDERS }

  has_one :shop

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/api/names_controller.rb
class Api::NamesController < ApiController
  def show
    user = User.find(params[:user_id])
    render json: { id: user.id, name: user.name }, status: :ok
  end
end

app/controllers/api/shops_controller.rb
class Api::ShopsController < ApiController
  before_action :find_user
  before_action :check_shop

  def show
  end

  def create
    head :conflict and return if @user.shop.present?
    shop = @user.create_shop(shop_params)
    if shop.valid?
      render :show, status: :created
    else
      render json: { errors: shop.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @user.shop.update(shop_params)
      render :show, status: :ok
    else
      render json: { errors: @user.shop.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @user.shop.destroy
    render :show
  end

  private

  def find_user
    @user = User.find params[:user_id]
  end

  def check_shop
    case action_name
    when 'create'
      head :conflict and return if @user.shop.present?
    else
      head :not_found and return if @user.shop.blank?
    end
  end

  def shop_params
    params.require(:shop).permit(:name, :description)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  before_action :set_user, only: [:show, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render :show, status: :created
    else
      render json: { errors: @user.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @user.update user_params
      render :show, status: :ok
    else
      render json: { errors: @user.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    render :show, status: :ok
  end

  def count
    render json: { count: User.count }, status: :ok
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :age,
                                 :gender,
                                 address: User::ADDRESS_ACCESSOR_KEYS)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  rescue_from Mongoid::Errors::DocumentNotFound, with: :not_found_handler

  protected

  def not_found_handler(_exception)
    head :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: %i(index new create)

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User is created!'
      redirect_to users_path
    else
      render :new, flash: { errors: @user.errors.full_messages }
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, flash: { success: "User #{@user.name} is deleted!" }
  end

  protected

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :age,
                                 :gender,
                                 address: User::ADDRESS_ACCESSOR_KEYS)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnboardingTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ng-app='userApp'>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.slim
h3 = "Edit User: #{@user.name}"
.user-form ng-controller='UsersEditController'
  form.user-edit-form name='userForm' novalidate='' data-user-id="#{@user.id}"
    .form-group
      label for='firstName' First Name
      input.form-control name='firstName' ng-model='user.firstName' required=''
      .error ng-show="userForm.firstName.$dirty && userForm.firstName.$invalid"
        small.error ng-show="userForm.firstName.$error.required"
          | First Name required

    .form-group
      label for='lastName' Last Name
      input.form-control name='lastName' ng-model='user.lastName' required=''
      .error ng-show="userForm.lastName.$dirty && userForm.lastName.$invalid"
        small.error ng-show="userForm.lastName.$error.required"
          | Last Name required

    .form-group
      label for='age' Age
      input.form-control type='number' name='age' ng-model='user.age' required='' ng-min='0'
      .error ng-show="userForm.age.$dirty && userForm.age.$invalid"
        small.error ng-show="userForm.age.$error.required"
          | Age required
      .error ng-show="userForm.age.$dirty && userForm.age.$invalid"
        small.error ng-show="userForm.age.$error.min"
          | Age must be postive

    .form-group
      label for='gender' Gender
      br
      |&nbsp Male &nbsp
      input type='radio' value='male' name='gender' ng-model=' user.gender'  checked='' required=''
      |&nbsp Female &nbsp
      input type='radio' value='female' name='gender' ng-model='user.gender'
      |&nbsp Others &nbsp
      input type='radio' value='others' name='gender' ng-model='user.gender'
      .error ng-show="userForm.gender.$dirty && userForm.gender.$invalid"
        small.error ng-show="userForm.gender.$error.min"
          | Gender must be postive

    .form-group
      label for='addressCountry' Country
      input.form-control name='addressCountry' ng-model='user.address.country'

    .form-group
      label for='addressAddress1' Address 1
      input.form-control name='addressAddress1' ng-model='user.address.address1'

    .form-group
      label for='addressAddress2' Address 2
      input.form-control name='addressAddress2' ng-model='user.address.address2'

    .form-group
      button.button.button-small.button-primary ng-disabled='userForm.$pristine || userForm.$invalid' ng-click='updateUserForm()' Submit

app/views/users/index.html.slim
h3 User Lists

- if flash[:notice]
  .alert.alert-notice role="alert" = flash[:notice]
- if flash[:success]
  .alert.alert-success role="alert" = flash[:success]

.user-app ng-controller='UsersEditController'
  span Users Count: &nbsp
  span#user-count = @users.count
  .new-user
    = link_to 'New', new_user_path, class: 'btn btn-small btn-success', id: 'new-user-button'
  table.table.table-hover
    thead
      th User
      th Action
    tbody
      - @users.each do |user|
        tr
          td.user-name = user.name
          td
            = link_to 'Show', user_path(user), class: 'btn btn-small btn-info'
            = link_to 'Edit', '#', 'ng-click' => "emitEditUser($event, '#{user.id}')", class: 'btn btn-small btn-primary'
            = link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'You know what you are going to do?' }, class: 'btn btn-small btn-danger'
  .user-edit ng-show='renderEditUser'
    user-form

app/views/users/new.html.slim
h3 New User
= form_for(@user, url: users_path, html: { role: "form" }) do |f|
  - if @user.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@user.errors.count,"error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg

  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'

  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'

  .form-group
    = f.label :age
    = f.number_field :age, class: 'form-control'

  .form-group
    = f.label :gender
    | &nbsp Male: &nbsp
    = f.radio_button :gender, 'male', checked: true
    | &nbsp Female: &nbsp
    = f.radio_button :gender, 'female'
    | &nbsp Others: &nbsp
    = f.radio_button :gender, 'others'

  .form-group
    = f.label :address, class: "col-sm-2 control-label"
    .col-sm-3
      | Country:
      input type="text" name="user[address][country]" id="user_address_country"
    .col-sm-3
      | Address 1:
      input type="text" name="user[address][address_1]" id="user_address_address_1"
    .col-sm-3
      | Address 2:
      input type="text" name="user[address][address_2]" id="user_address_address_2"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/users/show.html.slim
h3 User Name
= @user.name